apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: hello
  annotations:
    link.argocd.argoproj.io/external-link: https://hello.platform.local
spec:
  hosts:
  - hello.platform.local
  gateways:
  - platform/platform-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: hello.development.svc.cluster.local
        port:
          number: 80