apiVersion: v1
kind: Service
metadata: 
  name: postgres
spec:
  type: ClusterIP
  ports:
  - name: tcp
    port: 5432
    targetPort: 5432
    protocol: TCP
    appProtocol: TCP
  selector:
    app: postgres