apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - "./istio"
  - "./echo.yaml"
  - "./postgres"
patches:
  - path: "connection-checker.yaml"
    target:
      kind: Job
      annotationSelector: "await=service"
helmCharts:   
- name: base
  namespace: istio-system
  releaseName: istio-base
  repo: https://istio-release.storage.googleapis.com/charts
  version: ~1.20.1
  includeCRDs: true
  valuesInline:
    defaultRevision: default
- name: istiod
  namespace: istio-system
  releaseName: istiod
  repo: https://istio-release.storage.googleapis.com/charts
  version: ~1.20.1
  valuesInline:
    pilot:
      configMap: false
- name: gateway
  namespace: istio-system
  releaseName: istio-gateway
  repo: https://istio-release.storage.googleapis.com/charts
  version: ~1.20.1
  valuesInline:
    service:
      # Type of service. Set to "None" to disable the service entirely
      # type: LoadBalancer
