apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: platform-tls
  namespace: istio-system
spec:
  secretName: platform-tls
  dnsNames:
  - "*.platform.local"
  duration: 336h0m0s # 14d
  renewBefore: 168h0m0s # 7d
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - "digital signature"
    - "key encipherment"
  issuerRef:
    name: ca-issuer
    kind: ClusterIssuer
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: platform-gateway
  namespace: platform
spec:
  selector:
    istio: gateway
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      hosts:
        - "*/*.platform.local"
        - "*/platform.local"
      tls:
        mode: SIMPLE
        credentialName: platform-tls
