apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: nginx
          ports:
            - containerPort: 80
          command: ["/bin/sh", "-c"]
          args: ["echo 'hello demo viewers' > /usr/share/nginx/html/index.html && nginx -g 'daemon off;'"]
---
apiVersion: v1
kind: Service
metadata:
  name: web-app-service
spec:
  selector:
    app: web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: hello
  annotations:
    link.argocd.argoproj.io/external-link: https://hello.platform.local
spec:
  hosts:
  - hello.platform.local
  gateways:
  - platform/platform-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: web-app-service.development.svc.cluster.local
        port:
          number: 80