# This user has additional fields like email, first name, and last name.
apiVersion: user.keycloak.crossplane.io/v1alpha1
kind: User
metadata:
  name: developers-ds
spec:
  forProvider:
    realmIdRef: 
      name: developers-realm
    username: "ds@dsoderlund.consulting"
    initialPassword:
      - valueSecretRef:
          name: crossplane-keycloak-secret
          key: admin-password
          namespace: crossplane-system
    email: "ds@dsoderlund.consulting"
    emailVerified: true
    firstName: "David"
    lastName: "Söderlund"
  providerConfigRef:
    name: keycloak-config
---
apiVersion: user.keycloak.crossplane.io/v1alpha1
kind: Roles
metadata:
  name: developers-ds-roles
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  forProvider:
    realmIdRef: 
      name: developers-realm
    userIdRef: 
      name: developers-ds
    roleIdsRefs: 
      - name: "builtin-developers-realm-realm-admin"
  providerConfigRef:
    name: keycloak-config
---
apiVersion: user.keycloak.crossplane.io/v1alpha1
kind: Groups
metadata:
  name: developers-ds-groups
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  forProvider:
    realmIdRef: 
      name: developers-realm
    userIdRef: 
      name: developers-ds
    groupIdsRefs: 
      - name: "argocd-admin"
  providerConfigRef:
    name: keycloak-config
