apiVersion: v1
kind: Secret
metadata:
  name: crossplane-keycloak-secret
  namespace: platform
stringData:
  oap-password: oqoVVhGECYJRPkJ5OrixYJ3tki5nRg53
  admin-password: demofördaniel
  argocd-password: hbeT0fKekzgT0fGPMYV6On9cRcSHiU8b