apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: oauth2-proxy
resources:
  - "./cm.yaml"
  - "./redis-secret.yaml"
  - "./secret.yaml"
  - "./create-client.yaml"
  - "./oap-from-helm-template.yaml"
configMapGenerator:
  - name: client-script
    files:
      - "./create-client.sh"
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    note: kustomize-generated

