## This file is used with helm template to generate oap-from-helm-template.yaml which is used in the kustomize to get oauth2proxy to work like we want

## helm template oauth2-proxy oci://registry-1.docker.io/bitnamicharts/oauth2-proxy -f 2_platform\oauth2proxy\oap-values.yaml > 2_platform\oauth2proxy\oap-from-helm-template.yaml
configuration:
  existingSecret: "oauth2-proxy-secret"
  existingConfigmap: "oauth2-proxy-cm"
redis:
  enabled: true
  architecture: "standalone"
  master:
    service:
      port: 6379
  replica:
    replicaCount: 1
  auth:
    enabled: true
    existingSecret: "oauth2-proxy-redis-secret"
    existingSecretPasswordKey: "redis-secret"