configuration:
  existingSecret: "oauth2-proxy-secret"
  existingConfigmap: "oauth2-proxy-cm"
redis:
  enabled: true
  architecture: "standalone"
  master:
    service:
      port: 6379
  replica:
    replicaCount: 1
  auth:
    enabled: true
    existingSecret: "oauth2-proxy-redis-secret"
    existingSecretPasswordKey: "redis-secret"