apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      labels:
        app: echoserver
        demo: first-demo
    spec:
      containers:
        - image: ealen/echo-server:latest
          imagePullPolicy: IfNotPresent
          name: echoserver
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
          envFrom:
            - configMapRef:
                name: echoserver-config
                optional: true
          resources:
            limits:
              cpu: "0.2"
              memory: "64Mi"
            requests:
              cpu: "0.1"
              memory: "32Mi"
