apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-cm
  labels:
    app: keycloak
data:
  KC_DB: "postgres"
  KC_HEALTH_ENABLED: "true"
  KC_PROXY: "edge"
  KC_LOG_LEVEL: 'info'
  KC_HOSTNAME: 'https://kc.platform.local'