apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak
spec:
  instances: 1
  bootstrap:
    initdb:
      database: keycloak
      owner: keycloak
      secret:
        name: keycloak-db-secret
  storage:
    size: 2Gi
  inheritedMetadata:
    annotations:
      proxy.istio.io/config: '{"holdApplicationUntilProxyStarts": true}'