apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-postgres-cluster
  namespace: platform
spec:
  instances: 1
  storage:
    size: 2Gi
  inheritedMetadata:
    annotations:
      proxy.istio.io/config: '{"holdApplicationUntilProxyStarts": true}'