apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: platform
resources:
  - "./kc-deployment.yaml"
  - "./kc-svc.yaml"
  - "./kc-vs.yaml"
  - "./kc-cm.yaml"
patches:
- target:
    version: v1
    kind: ConfigMap
    name: keycloak-cm
  path: ./keycloak-admin-patch.yaml