apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmCharts:
  - name: reloader
    releaseName: reloader
    namespace: platform
    repo: https://stakater.github.io/stakater-charts
    version: 1.0.101
    valuesInline:
      reloader:
        namespaceSelector: "stakater-reloader=enabled"
