# This user has additional fields like email, first name, and last name.
apiVersion: user.keycloak.crossplane.io/v1alpha1
kind: User
metadata:
  name: guest-user
spec:
  forProvider:
    realmIdRef: 
      name: developers-realm
    username: "guest"
    email: "guest@dsoderlund.consulting"
    firstName: "Guest"
    lastName: "User"
  providerConfigRef:
    name: keycloak-config
---
apiVersion: user.keycloak.crossplane.io/v1alpha1
kind: Roles
metadata:
  name: guest-user-developers-realm
spec:
  forProvider:
    realmIdRef: 
      name: developers-realm
    userIdRef: 
      name: guest-user
    roleIdsRefs:
      name: builtin-developers-realm-realm-management-manage-realm