apiVersion: keycloak.crossplane.io/v1alpha1
kind: XBuiltinObjects
metadata:
  name: keycloak-builtin-objects-developers-realm
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  providerConfigName: keycloak-config
  providerSecretName: keycloak-credentials
  realm: developers-realm
  builtinClients: 
    - account
    - account-console
    - admin-cli
    - broker
    - realm-management
    - security-admin-console
  builtinRealmRoles:
    - offline_access
    - uma_authorization
    - admin
    - default-roles-developers-realm
    - create-realm
  builtinAuthenticationFlows:
    - browser
