apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  name: oauth2-proxy
  annotations:
    dsoderlund.consulting/rendered-by: yaml
    dsoderlund.consulting/managed-by: crossplane
spec:
  providerConfigRef:
    name: keycloak-config
  deletionPolicy: Orphan
  managementPolicies: ["*"]
  forProvider:
    realmIdRef:
      name: developers-realm
    accessType: CONFIDENTIAL
    clientId: oauth2proxy
    clientSecretSecretRef:
      name: crossplane-keycloak-secret
      key: oap-password
      namespace: platform
    name: oauth2proxy
    description: "Applied by Crossplane (changes made in UI will be overwritten)"
    validRedirectUris:
      - "*"
    standardFlowEnabled: true
    serviceAccountsEnabled: true
