apiVersion: user.keycloak.crossplane.io/v1alpha1
kind: Roles
metadata:
  name: developers-admin-roles
spec:
  forProvider:
    realmIdRef: 
      name: developers-realm
    userIdRef: 
      name: developers-admin
    roleIdsRefs: 
      - name: "builtin-developers-realm-realm-admin"
  providerConfigRef:
    name: keycloak-config