apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: 'development'
resources:
  - 'admin-user.yaml'
  - 'admin-groups.yaml'
  - 'admin-roles.yaml'
patches:
  - target:
      group: user.keycloak.crossplane.io
      kind: User
      name: developers-admin
    path: ./admin-patch.yaml