---
apiVersion: group.keycloak.crossplane.io/v1alpha1
kind: Group
metadata:
  name: argocd-admin
  annotations:
    dsoderlund.consulting/rendered-by: yaml
    dsoderlund.consulting/managed-by: crossplane
    argocd.argoproj.io/sync-wave: "2"
spec:
  forProvider:
    realmIdRef:
      name: master
    name: argocd-admin
  providerConfigRef:
    name: keycloak-config
---
apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: ClientScope
metadata:
  name: groups
  annotations:
    dsoderlund.consulting/rendered-by: yaml
    dsoderlund.consulting/managed-by: crossplane
    argocd.argoproj.io/sync-wave: "2"
spec:
  providerConfigRef:
    name: keycloak-config 
  forProvider:
    realmIdRef:
      name: master
    name: groups
    includeInTokenScope: true
    consentScreenText: "Access to group membership"
    guiOrder: 0
---
apiVersion: client.keycloak.crossplane.io/v1alpha1
kind: ProtocolMapper
metadata:
  name: groups-mapper
  annotations:
    dsoderlund.consulting/rendered-by: yaml
    dsoderlund.consulting/managed-by: crossplane
    argocd.argoproj.io/sync-wave: "2"
spec:
  providerConfigRef:
    name: keycloak-config 
  forProvider:
    realmIdRef:
      name: master
    clientScopeIdRef:
      name: groups
    name: groups
    protocol: openid-connect
    protocolMapper: "oidc-group-membership-mapper"
    config:
      full.path: "false"
      id.token.claim: "true"
      access.token.claim: "true"
      claim.name: "groups"
      userinfo.token.claim: "true"
---
apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: Client
metadata:
  name: argocd
  annotations:
    dsoderlund.consulting/rendered-by: yaml
    dsoderlund.consulting/managed-by: crossplane
    argocd.argoproj.io/sync-wave: "2"
spec:
  providerConfigRef:
    name: keycloak-config
  deletionPolicy: Orphan
  managementPolicies: ["*"]
  forProvider:
    realmIdRef: 
      name: master
    accessType: CONFIDENTIAL
    clientId: argocd
    clientSecretSecretRef:
      name: crossplane-keycloak-secret
      key: argocd-password
      namespace: crossplane-system
    name: argocd
    description: "Applied by Crossplane (changes made in UI will be overwritten)"
    validRedirectUris:
      - "http://localhost:8085/auth/callback"
      - "https://argocd.platform.local/*"
    standardFlowEnabled: true
    serviceAccountsEnabled: true
    frontchannelLogoutEnabled: true
---
apiVersion: openidclient.keycloak.crossplane.io/v1alpha1
kind: ClientDefaultScopes
metadata:
  name: argocd-scopes
  annotations:
    dsoderlund.consulting/rendered-by: yaml
    dsoderlund.consulting/managed-by: crossplane
    argocd.argoproj.io/sync-wave: "2"
spec:
  providerConfigRef:
    name: keycloak-config
  forProvider:
    realmIdRef:
      name: master
    clientIdRef:
      name: argocd
    defaultScopes:
      - openid
      - profile
      - email
      - groups

---