apiVersion: keycloak.crossplane.io/v1alpha1
kind: XBuiltinObjects
metadata:
  name: keycloak-builtin-objects-master
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  providerConfigName: keycloak-config
  providerSecretName: keycloak-credentials
  realm: master
  builtinClients:
    - master-realm
  builtinRealmRoles:
    - admin
  builtinAuthenticationFlows:
    - browser
