kind: AuthorizationPolicy
apiVersion: security.istio.io/v1beta1
metadata:
  name: ext-authz-oauth2-proxy
spec:
  selector:
    matchLabels:
      istio: gateway
  action: CUSTOM
  provider:
    name: oauth2-proxy
  rules:
    - to:
        - operation:
            hosts: ["*.platform.local"]
            notPaths: ["/oauth2/callback", "/auth"]
            notHosts: ["echo.platform.local"]
