apiVersion: v1
kind: ConfigMap
metadata:
  name: istio
  labels:
    app.kubernetes.io/instance: istiod 
    install.operator.istio.io/owning-resource: unknown 
    istio.io/rev: default  
    operator.istio.io/component: Pilot
data:
  mesh: |-
    enablePrometheusMerge: true
    enableTracing: true
    outboundTrafficPolicy:
      mode: ALLOW_ANY
    trustDomain: cluster.local
    extensionProviders:
    - name: oauth2-proxy
      envoyExtAuthzHttp:
        service: oauth2-proxy.oauth2-proxy.svc.cluster.local
        port: 80
        timeout: 1.5s
        includeHeadersInCheck: ["authorization", "cookie", "x-forwarded-email"]
        headersToUpstreamOnAllow: ["x-forwarded-access-token", "x-forwarded-email", "path", "x-auth-request-user", "x-auth-request-email", "x-auth-request-access-token"]
        headersToDownstreamOnDeny: ["content-type", "set-cookie"]
    - name: otel-tracing
      opentelemetry:
        port: 4317
        service: opentelemetry-collector.observability.svc.cluster.local
        resource_detectors:
          environment: {}
  meshNetworks: 'networks: {}'

