apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
resources:
  - "./mtls-strict.yaml"
  - "./istio-cm.yaml"
  - "./auth-policy.yaml"
  - "./istio-telemetry.yaml"
helmCharts:

  - name: base
    namespace: istio-system
    releaseName: istio-base
    repo: https://istio-release.storage.googleapis.com/charts
    version: ~1.27.1
    includeCRDs: true
    valuesInline:
      defaultRevision: default
  - name: istiod
    namespace: istio-system
    releaseName: istiod
    repo: https://istio-release.storage.googleapis.com/charts
    version: ~1.27.1
    valuesInline:
      pilot:
        configMap: false
      profile: ambient
  - name: gateway
    namespace: istio-system
    releaseName: istio-gateway
    repo: https://istio-release.storage.googleapis.com/charts
    version: ~1.27.1
    valuesInline:
      service:
        # Type of service. Set to "None" to disable the service entirely
        # type: LoadBalancer
  - name: cni
    namespace: istio-system
    releaseName: istio-cni
    repo: https://istio-release.storage.googleapis.com/charts
    version: ~1.27.1
    valuesInline:
      profile: ambient
  - name: ztunnel
    namespace: istio-system
    releaseName: ztunnel
    repo: https://istio-release.storage.googleapis.com/charts
    version: ~1.27.1
