apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crossplane-system
resources:
  - create-client.yaml
  - crossplane-keycloak-secret.yaml
configMapGenerator:
  - name: client-script
    files:
      - "./create-client.sh"
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    note: kustomize-generated

helmCharts:
  - name: crossplane
    namespace: crossplane-system
    releaseName: crossplane
    repo: https://charts.crossplane.io/stable
    version: 2.0.2
patches:
  - target:
      group: pkg.crossplane.io
      kind: Function
    patch: |
      - op: add
        path: /metadata/annotations
        value: {"argocd.argoproj.io/sync-wave": "1", "argocd.argoproj.io/sync-options": "SkipDryRunOnMissingResource=true"}
  - target:
      version: v1
      kind: Secret
      name: crossplane-keycloak-secret
    path: ./crossplane-keycloak-secret-patch.yaml