apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crossplane-system
resources:
  - "./create-client.yaml"
configMapGenerator:
  - name: client-script
    files:
      - "./create-client.sh"
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    note: kustomize-generated
helmCharts:
  - name: crossplane
    namespace: crossplane-system
    releaseName: crossplane
    repo: https://charts.crossplane.io/stable
    version: 2.0.2