apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crossplane-system
resources:
  - "./provider-keycloak.yaml"
  - "./provider-config-keycloak.yaml"
secretGenerator:
  - name: keycloak-credentials
    type: Opaque
    literals:
      - credentials={"client_id":"crossplane","client_secret":"xppw_LnaEt79B47CxPEafJpXx","url":"http://kc.platform.local","realm":"master","base_Path":"/"} 
      # ,"root_ca_certificate":""
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    note: kustomize-generated
