apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: crossplane-system
resources:
  - "./provider-keycloak.yaml"
  - "./provider-config-keycloak.yaml"
  - "./keycloak-credentials.yaml"