apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  package: xpkg.upbound.io/crossplane-contrib/provider-keycloak:v0.21.0