# these are not actually secret, never check kubernetes secrets into git. Use sealed-secrets or similar.
# This is used as a way of deploying already known argocd secrets into the cluster.

apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
type: Opaque
data:
  oidc.keycloak.clientSecret: aGJlVDBmS2VremdUMGZHUE1ZVjZPbjljUmNTSGlVOGI=
  admin.password: bm90dXNlZA==
