apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - "./argocd-vs.yaml"
  - "./argocd-secret.yaml"
  - "./create-client.yaml"
configMapGenerator:
  - name: client-script
    files:
      - "./create-client.sh"
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    note: kustomize-generated
helmCharts:
- name: argo-cd
  releaseName: argocd
  repo: https://argoproj.github.io/argo-helm
  version: 5.52.0
  valuesInline:
    configs:
      cm:
        url: https://argocd.platform.local
        admin.enabled: "false"
        oidc.config: |
          name: keycloak
          issuer: https://kc.platform.local/realms/master
          clientID: argocd
          clientSecret: $oidc.keycloak.clientSecret
          requestedScopes: ["openid", "profile", "email", "groups"]
        kustomize.buildOptions: --enable-helm
        application.resourceTrackingMethod: annotation
      rbac:
        policy.csv: |
          g, argocd-admin, role:admin
          g, argocd-viewer, role:readonly
      params:
        server.insecure: true
      secret:
        createSecret: false
    dex:
      enabled: false
    